dist: xenial
sudo: true
cache:
  - directories:
    - /var/lib/docker
env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - docker -D info
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - travis_retry cp .env.dist .env
  - export GIT_COMMIT=`echo $TRAVIS_BRANCH | tr "[:upper:]" "[:lower:]" | sed "s/[^a-zA-Z0-9-]/-/g" | sed "s/-$//g" | tr -d '\n' | tr -d '\r'`
  - docker build .docker/node$(DOCKER_NODE_VERSION)-base/ \
    --tag $(DOCKER_SERVER_HOST):$(DOCKER_SERVER_PORT)/$(DOCKER_PROJECT_PATH)/node$(DOCKER_NODE_VERSION)-base:$(DOCKER_IMAGE_VERSION) \
    --build-arg DOCKER_SERVER_HOST=$(DOCKER_SERVER_HOST) \
    --build-arg DOCKER_SERVER_PORT=$(DOCKER_SERVER_PORT) \
    --build-arg DOCKER_PROJECT_PATH=$(DOCKER_PROJECT_PATH) \
    --build-arg DOCKER_NODE_VERSION=$(DOCKER_NODE_VERSION) \
    --build-arg DOCKER_IMAGE_VERSION=$(DOCKER_IMAGE_VERSION)
  - docker-compose build --pull

script:
  - docker-compose -f docker-compose-ci.yml run app yarn
  - docker-compose -f docker-compose-ci.yml run app yarn lint
  - docker-compose -f docker-compose-ci.yml run app yarn build-ci


deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
