version: "3.4"
services:
  app:
    image: ${DOCKER_SERVER_HOST}:${DOCKER_SERVER_PORT}/${DOCKER_PROJECT_PATH}/node-dev:${DOCKER_IMAGE_VERSION}
    stop_signal: INT
    user: 1000:1000
    tty: true
    depends_on:
      - redis
    volumes:
      - ./.docker/app/MinterNode/config/:/minter/config/:ro
      - minter_data:/minter/data/
      - tendermint_data:/minter/tmdata/

      - ./app/:/app/:rw
    env_file:
      - .env
    ports:
      - ${NODE_API_PORT:-8841}:8841
      - ${APP_API_PORT:-4000}:4000

  redis:
    image: redis:4
    command: 'redis-server /usr/local/etc/redis/redis.conf --loglevel verbose'
    volumes:
      - ./.docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data/:rw
    ports:
      - ${REDIS_PORT}:6379



volumes:
  redis_data:
  minter_data:
  tendermint_data:
