version: "3.7"
services:
  app:
    image: ${DOCKER_SERVER_HOST}/${DOCKER_PROJECT_PATH}/node${DOCKER_NODE_VERSION}-base:${DOCKER_IMAGE_VERSION}
    stop_signal: INT
    user: 1000:1000
    tty: true
    volumes:
      - ./:/app:rw
      - ~/.cache/yarn:/home/node/.cache/yarn:rw

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:4
    volumes:
      - redis_data:/data/:rw
    ports:
      - ${REDIS_PORT}:6379



volumes:
  redis_data:
